### ISSUE TITLE
Unused AgnosticDatabase in Method Signatures

### ISSUE THREAD

**Issue by Osc44r** [mongodb-labs/full-stack-fastapi-mongodb#26]
Hi there. I've noticed that AgnosticDatabase is included in several method signatures, but it doesn't seem to be used within the methods themselves. The application appears to be functioning on AIOEngine. In my project cases, I have already removed AgnosticDatabase. If it is needed in the future, I can create a pull request to reintroduce it. Could you kindly clarify if there are plans to utilize AgnosticDatabase in the future or if it will be removed from the method signatures? Thank you.

**Comment by Jibola** [comment]
Hey @Osc44r,

Great question! I can say we will be removing the redundant references to the `AgnosticDatabase` and I have gone ahead and tracked this issue as a formal [JIRA ticket](https://jira.mongodb.org/browse/PYTHON-4235) where you can track progress. If you'd like to provide the contribution yourself, that would be more than welcomed and we'd happily provide review. :)
