### ISSUE TITLE
Removing hardcoded paths

### ISSUE THREAD

**Issue by Mrostgaard** [mongodb-labs/full-stack-fastapi-mongodb#49]
https://github.com/mongodb-labs/full-stack-fastapi-mongodb/blob/bdc9590985d5b3a68b0f685dc266c0a348a1c3b2/%7B%7Bcookiecutter.project_slug%7D%7D/frontend/tsconfig.json#L22-L23

These should probably just look like:
```    
"paths": {
      "@": ["./"],
      "@/*": ["./*"]
    }
```

Instead of the hardcoded path that exists at the moment.

**Comment by Jibola** [comment]
Thanks for the suggestion. We've merged the change!
