### ISSUE TITLE
running example Error: Type error: This kind of expression is always truthy.

### ISSUE THREAD

**Issue by shouari** [mongodb-labs/full-stack-fastapi-mongodb#55]
hello 
while running the exmaple (docker compose build) I'm constanatly facing this error `Type error: This kind of expression is always truthy.`
Can anyone help with this?

Screenshot for ref.
![image](https://github.com/user-attachments/assets/9fbfa653-1107-4ea0-9286-110448dc69e4)

**Comment by shouari** [comment]
Issue was solved by changing from this code:
`switch (condition) {
    case "required":
        return <div className={style}>This field is required.</div>;
    case "minLength" || "maxLength":
        return (
            <div className={style}>
                Your password must be between 8 and 64 characters long.
            </div>
        );
}`

to this: `switch (condition) {
    case "required":
        return <div className={style}>This field is required.</div>;
    case "minLength":
    case "maxLength":
        return (
            <div className={style}>
                Your password must be between 8 and 64 characters long.
            </div>
        );
}`
in the indicated files. There are 3 or 4 to be corrected

**Comment by Cajuteq** [comment]
For people who have that in the codebase and are asking themself what happened, it was a hidden bug that was revealed by Typescript 5.6 update. Here is the PR https://github.com/microsoft/TypeScript/pull/59217
